# -*- coding: utf-8 -*-
"""Cruzamento variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K25jtp9l59CY0kP7fYko_DkWhUYDZWmC

## Método 2 
https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html
***
"""

import pandas as pd

dados = pd.read_csv('dados_pnad.csv')

freq = pd.crosstab(dados.Sexo, dados.Cor)
freq

pct = pd.crosstab(dados.Sexo, dados.Cor, normalize = True) * 100
pct

sexo = {0: 'Masc', 1: 'Fem'}
cor = {0: 'ind', 2: 'branco', 4: 'preto',6: 'amarelo',8: 'parda',9: 'sem declaracao'}

freq.rename(index = sexo, inplace = True)
freq.rename(columns = cor, inplace = True)
freq

pct.rename(index = sexo, inplace = True)
pct.rename(columns = cor, inplace = True)
pct

combinacao = pd.crosstab(dados.Sexo, dados.Cor, aggfunc= 'mean', values = dados.Renda)
combinacao.rename(index = sexo, inplace = True)
combinacao.rename(columns = cor, inplace = True)
combinacao

